
services:
  email-notifier:
    build:
      context: email-notifier
      args:
        TEST_PATH: '/tests'
        CRON_SCHEDULE: ${EMAIL_CRON_SCHEDULE:-* * * * *}
        OPENSSL_PWD: ${EMAIL_OPENSSL_PWD:?e.g. changeme}
    image: hs_email-notifier:develop
    pull_policy: never
    environment:
      HOST: ${EMAIL_HOST:?e.g. required.email.host}
      PORT: ${EMAIL_PORT:?e.g. 587}
      USER: ${EMAIL_USER:?e.g. requiredUser}
      DISPLAY_NAME: ${EMAIL_DISPLAY_NAME:-}
      FROM: ${EMAIL_FROM:-}
      RECIPIENTS: ${EMAIL_RECIPIENTS:?e.g. mail1@example.com:mail2@example.com}
    volumes:
      - ./email-notifier/tests/emails:/emails
      - ./email-notifier/tests/logs:/logs
      - ./email-notifier/src:/src
      - ./email-notifier/tests:/tests
  storage-health-check:
    build:
      context: storage-health-check
      args:
        TEST_PATH: '/tests'
    image: hs_storage-health-check:develop
    pull_policy: never
    volumes:
      - ./storage-health-check/src:/src
      - ./storage-health-check/tests:/tests
networks:
  default:
    name: hs-dev
