#!/bin/sh

SHOW_RESULT=''
STATS_RESULT=''
SCRUB_RESULT=''


TMP_OUTPUT=$(btrfs fi show $1)
TMP_ERRORS=$(echo "$TMP_OUTPUT" | grep 'devid' | awk '{print $6}' | sort | uniq | wc -l)
if [ "$TMP_ERRORS" -gt 1 ]; then
    SHOW_RESULT="$TMP_OUTPUT"
fi


TMP_OUTPUT=$(btrfs device stats $1)
TMP_ERRORS=$(echo "$TMP_OUTPUT" | awk '{print $NF}' | sort | uniq)
if [ "$TMP_ERRORS" != '0' ]; then
    STATS_RESULT="$TMP_OUTPUT"
fi


TMP_OUTPUT=$(btrfs scrub start -B $1)
TMP_ERRORS=$(echo "$TMP_OUTPUT" | grep 'Error summary:')
TMP_ERRORS="${TMP_ERRORS/Error summary:/}"
TMP_ERRORS="${TMP_ERRORS#"${TMP_ERRORS%%[![:space:]]*}"}"
TMP_ERRORS="${TMP_ERRORS%"${TMP_ERRORS##*[![:space:]]}"}"
if [ "$TMP_ERRORS" != "no errors found" ]; then
    SCRUB_RESULT="$TMP_OUTPUT"
fi

# Print result

if [ -n "$SHOW_RESULT" -o -n "$STATS_RESULT" -o -n "$SCRUB_RESULT" ]; then
    RESULT="$1"
    if [ -n "$SHOW_RESULT" ]; then
        RESULT="$RESULT\n\n$SHOW_RESULT"
    fi
    if [ -n "$STATS_RESULT" ]; then
        RESULT="$RESULT\n\n$STATS_RESULT"
    fi
    if [ -n "$SCRUB_RESULT" ]; then
        RESULT="$RESULT\n\n$SCRUB_RESULT"
    fi
    echo -e "$RESULT$(divider)" >> "$2"
fi
