#!/bin/sh

KEY_FILE='/credentials/email.key'

if test ! -f "${KEY_FILE}"; then
  echo 'Email key file not found, please enter the email password to generate a key file:'
  read -r DB_PWD
  ENCRYPTED_DB_PWD=$(echo "${DB_PWD}" | openssl enc -base64 -e -aes-256-cbc -salt -pass pass:"${ENCRYPTION_KEY}" -pbkdf2)
  echo "${ENCRYPTED_DB_PWD}" > "${KEY_FILE}"
  chmod 0400 $KEY_FILE
fi

echo "$CRON_SCHEDULE send-emails" >> /var/spool/cron/crontabs/root

crond -f -l 2
