#!/bin/sh

mail_dir='/emails'
exit_code=0

# Check if there are any files in the directory.
files=$(ls -p "$mail_dir" | grep -v /)
if [ -n "$files" ]; then

    # Replace colons with spaces.
    recipients=$(echo "$RECIPIENTS" | tr ':' ' ')

    # Loop through all files in the directory.
    while IFS= read -r file; do
        filepath="$mail_dir/$file"

        # Get the subject.
        subject=$(basename "$file")

        # Get the body.
        body=$(cat "$filepath")

        # Check if $FROM is set; if not, $USER is used.
        sender=$([ -n "$FROM" ] && echo "$FROM" || echo "$USER")

        # Check if $DISPLAY_NAME is set and not empty.
        if [ -n "$DISPLAY_NAME" ]; then
            # Format as "Display Name <email>".
            sender="$DISPLAY_NAME <$sender>"
        fi

        # Build the message.
        message="From: $sender\nTo: $recipients\nSubject: $subject\n$body"

        # Send email.
        echo -e "$message" | msmtp \
            --auth=on \
            --tls=on \
            --tls-trust-file='/etc/ssl/certs/ca-certificates.crt' \
            --logfile=- \
            --logfile-time-format=none \
            --host="$HOST" \
            --port="$PORT" \
            --user="$USER" \
            --passwordeval='openssl enc -d -aes-256-cbc -salt -k "$OPENSSL_PWD" -pbkdf2 -iter 100000 -in /etc/credential' \
            --read-envelope-from \
            --read-recipients

        tmp_exit_code=$?
        # If the email was sent correctly, the file is deleted.
        if [ $tmp_exit_code -eq 0 ]; then
            if [ -f "$filepath" ]; then
                rm "$filepath"
            fi
            echo "Email '$file' sent successfully."
        else
            exit_code="$tmp_exit_code"
            echo "Error during sending the '$file' email." >&2
        fi
    done < <(echo "$files")
else
    echo 'No email to send.'
fi
exit $exit_code
